### ISSUE TITLE
Better documentation on check_command annotations

### ISSUE THREAD

**Issue by davidasnider** [gyselroth/kube-icinga#24]
#### Is your feature request related to a problem? Please describe
I have created a command that will check Kubernetes objects, it requires vars.name, vars.namespace, vars.type (service, deployment, etc). As far as I can tell, I can create an annotation that creates a check_command override, but I cannot see how to specify what the vars.* should be, can I set those in an annotation?

#### Describe the solution you'd like
A few examples on how to do this in the documentation would be good.  As an example, there is extensive metadata defined in the Kubernetes variable for the service, is there a way to address that in the check_command?  Or is there a way to specify it in a definition annotation?

#### Describe alternatives you've considered
I've considered writing a custom check command for each service to override, but this doesn't feel like it will scale very well

#### Additional context
Here are the check_command definitions for Icinga and Kubernetes 

```
object CheckCommand "check_kube" {
        import "plugin-check-command"
        command = [ "/etc/icinga2/scripts/check_kube.sh" ]
        arguments = {
          "-t" = "$kube_type$"
          "-c" = "$kube_check$"
          "-n" = "$kube_namespace$"
          "-o" = "$kube_object$"
        }
}

object CheckCommand "check_kube_deployment" {
        import "plugin-check-command"
        command = [ "/etc/icinga2/scripts/check_kube.sh" ]
        arguments = {
          "-t" = "deployment"
          "-c" = "Available"
          "-n" = "$kube_namespace$"
          "-o" = "$kube_object$"
        }
}
```

**Comment by davidasnider** [comment]
If you can give me the quick syntax, I'll be happy to submit a PR on the Readme.

**Comment by raffis** [comment]
> A few examples on how to do this in the documentation would be good. As an example, there is extensive metadata defined in the Kubernetes variable for the service, is there a way to address that in the check_command? Or is there a way to specify it in a definition annotation?

You should be able to access it using something like `$service.vars.kubernetes.meta.namespace$`. See https://icinga.com/docs/icinga2/latest/doc/03-monitoring-basics/#evaluation-order

Using the kube-icinga/check_command annotation you are only able to set a simple icinga check_command, nothing more. You might use kube-icinga/definition which allows you to statically define the icinga service. But as I said its static and if you have loads of objects probably not what you want. This is only meant for specific overwrites for whatever reason.

May I ask what your use case is? Why do you want to define a custom check and for what kubernetes resources?

**Comment by davidasnider** [comment]
My use case was to check things like deployments and replica sets and things.  So, for a service, it might be up, but perhaps I have one pod in a crash loop but still a few pods running. I'd want to add a check for the deployments.

**Comment by raffis** [comment]
> My use case was to check things like deployments and replica sets and things. So, for a service, it might be up, but perhaps I have one pod in a crash loop but still a few pods running. I'd want to add a check for the deployments.

Pods/Deployments aren't supported yet, please see the support for resources here: https://github.com/gyselroth/kube-icinga#resource-types
However pods support is planned #13. I just need to check a couple of things like the stability of the icinga api with quite a lot of changes and restarts since pods are likely to be changing a lot during a deployment lifetime.

**Comment by davidasnider** [comment]
Yeah, much more interested in deployment health 
    	
    	

    	Get Outlook for iOS
    
  




On Thu, Sep 12, 2019 at 1:09 AM -0600, "raffis" <notifications@github.com> wrote:













My use case was to check things like deployments and replica sets and things. So, for a service, it might be up, but perhaps I have one pod in a crash loop but still a few pods running. I'd want to add a check for the deployments.



Pods/Deployments aren't supported yet, please see the support for resources here: https://github.com/gyselroth/kube-icinga#resource-types

However pods support is planned #13. I just need to check a couple of things like the stability of the icinga api with quite a lot of changes and restarts since pods are likely to be changing a lot during a deployment lifetime.

**Comment by davidasnider** [comment]
No worries, I think Deployment would be better as an additional object, but it's of course your call.  If you did deployment, my use case would go away :D
